M48
; DRILL file {KiCad 6.0.0} date Tue 04 Jan 2022 09:54:21 PM CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-04T21:54:21+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.1142Y-1.5354
X4.1142Y-2.3228
X6.2795Y-1.5354
X6.2795Y-2.3228
T0
M30
