M48
; DRILL file {KiCad (5.99.0-12650-g5c402a64ab)} date Fri 08 Oct 2021 10:01:27 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-10-08T22:01:27+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-12650-g5c402a64ab)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.8898Y-3.8543
X5.5669Y-4.0197
T0
M30
